"""Runtime-passive public API for Phase 1 parser contract modules."""

from __future__ import annotations

from carbonfactor_parser.parsers.adapter_registry_contract import (
    Phase1ParserAdapterDescriptor,
    Phase1ParserAdapterRegistry,
    create_phase1_parser_adapter_registry,
    get_phase1_parser_adapter_by_parser_key,
    get_phase1_parser_adapter_by_source_family,
    list_phase1_parser_adapter_descriptors,
)
from carbonfactor_parser.parsers.defra_desnz_adapter_contract import (
    DEFRA_DESNZ_PARSER_KEY,
    DEFRA_DESNZ_SOURCE_FAMILY,
    DefraDesnzParserAdapterDescriptor,
    describe_defra_desnz_parser_adapter,
)
from carbonfactor_parser.parsers.dry_run_boundary_contract import (
    ParserDryRunBoundaryResult,
    ParserDryRunBoundaryStatus,
    ParserDryRunBoundaryValidationIssue,
    ParserDryRunBoundaryValidationResult,
    ParserDryRunEligibility,
    ParserDryRunSummary,
    plan_parser_dry_run_boundary,
    validate_parser_dry_run_boundary_result,
)
from carbonfactor_parser.parsers.ghg_protocol_adapter_contract import (
    GHG_PROTOCOL_PARSER_KEY,
    GHG_PROTOCOL_SOURCE_FAMILY,
    GHGProtocolParserAdapterDescriptor,
    describe_ghg_protocol_parser_adapter,
)
from carbonfactor_parser.parsers.input_artifact_contract import (
    ParserInputArtifact,
    ParserInputArtifactValidationIssue,
    ParserInputArtifactValidationResult,
    create_phase1_parser_input_artifact,
    validate_parser_input_artifact,
)
from carbonfactor_parser.parsers.ipcc_efdb_adapter_contract import (
    IPCC_EFDB_PARSER_KEY,
    IPCC_EFDB_SOURCE_FAMILY,
    IpccEfdbParserAdapterDescriptor,
    describe_ipcc_efdb_parser_adapter,
)
from carbonfactor_parser.parsers.normalized_output_row_contract import (
    ParserNormalizedOutputBatch,
    ParserNormalizedOutputRow,
    ParserNormalizedOutputRowStatus,
    ParserNormalizedOutputRowValidationIssue,
    ParserNormalizedOutputRowValidationResult,
    create_parser_normalized_output_batch,
    create_parser_normalized_output_row,
    validate_parser_normalized_output_batch,
    validate_parser_normalized_output_row,
)
from carbonfactor_parser.parsers.parser_adapter_readiness_report_contract import (
    ParserAdapterReadinessCapability,
    ParserAdapterReadinessReport,
    ParserAdapterReadinessReportEntry,
    build_phase1_parser_adapter_readiness_report,
)
from carbonfactor_parser.parsers.parser_run_contract import (
    ParserRunContractValidationIssue,
    ParserRunContractValidationResult,
    ParserRunRequest,
    ParserRunResult,
    ParserRunStatus,
    ParserRunSummary,
    create_parser_run_request,
    create_parser_run_result,
    validate_parser_run_request,
    validate_parser_run_result,
)
from carbonfactor_parser.parsers.run_repository_contract import (
    ParserRunRepository,
    ParserRunRepositoryIssue,
    ParserRunRepositoryPersistResult,
    ParserRunRepositoryPersistStatus,
    ParserRunRepositoryValidationResult,
    create_parser_run_repository_persist_result,
    validate_parser_run_repository_inputs,
)
from carbonfactor_parser.parsers.validation_issue_contract import (
    ParserValidationIssue,
    ParserValidationIssueCollection,
    ParserValidationIssueSeverity,
    ParserValidationIssueValidationIssue,
    ParserValidationIssueValidationResult,
    create_parser_validation_issue,
    create_parser_validation_issue_collection,
    validate_parser_validation_issue,
    validate_parser_validation_issue_collection,
)


__all__ = (
    "DEFRA_DESNZ_PARSER_KEY",
    "DEFRA_DESNZ_SOURCE_FAMILY",
    "DefraDesnzParserAdapterDescriptor",
    "GHG_PROTOCOL_PARSER_KEY",
    "GHG_PROTOCOL_SOURCE_FAMILY",
    "GHGProtocolParserAdapterDescriptor",
    "IPCC_EFDB_PARSER_KEY",
    "IPCC_EFDB_SOURCE_FAMILY",
    "IpccEfdbParserAdapterDescriptor",
    "ParserAdapterReadinessCapability",
    "ParserAdapterReadinessReport",
    "ParserAdapterReadinessReportEntry",
    "ParserDryRunBoundaryResult",
    "ParserDryRunBoundaryStatus",
    "ParserDryRunBoundaryValidationIssue",
    "ParserDryRunBoundaryValidationResult",
    "ParserDryRunEligibility",
    "ParserDryRunSummary",
    "ParserInputArtifact",
    "ParserInputArtifactValidationIssue",
    "ParserInputArtifactValidationResult",
    "ParserNormalizedOutputBatch",
    "ParserNormalizedOutputRow",
    "ParserNormalizedOutputRowStatus",
    "ParserNormalizedOutputRowValidationIssue",
    "ParserNormalizedOutputRowValidationResult",
    "ParserRunContractValidationIssue",
    "ParserRunContractValidationResult",
    "ParserRunRequest",
    "ParserRunRepository",
    "ParserRunRepositoryIssue",
    "ParserRunRepositoryPersistResult",
    "ParserRunRepositoryPersistStatus",
    "ParserRunRepositoryValidationResult",
    "ParserRunResult",
    "ParserRunStatus",
    "ParserRunSummary",
    "ParserValidationIssue",
    "ParserValidationIssueCollection",
    "ParserValidationIssueSeverity",
    "ParserValidationIssueValidationIssue",
    "ParserValidationIssueValidationResult",
    "Phase1ParserAdapterDescriptor",
    "Phase1ParserAdapterRegistry",
    "build_phase1_parser_adapter_readiness_report",
    "create_parser_normalized_output_batch",
    "create_parser_normalized_output_row",
    "create_parser_run_repository_persist_result",
    "create_parser_run_request",
    "create_parser_run_result",
    "create_parser_validation_issue",
    "create_parser_validation_issue_collection",
    "create_phase1_parser_adapter_registry",
    "create_phase1_parser_input_artifact",
    "describe_defra_desnz_parser_adapter",
    "describe_ghg_protocol_parser_adapter",
    "describe_ipcc_efdb_parser_adapter",
    "get_phase1_parser_adapter_by_parser_key",
    "get_phase1_parser_adapter_by_source_family",
    "list_phase1_parser_adapter_descriptors",
    "plan_parser_dry_run_boundary",
    "validate_parser_dry_run_boundary_result",
    "validate_parser_input_artifact",
    "validate_parser_normalized_output_batch",
    "validate_parser_normalized_output_row",
    "validate_parser_run_repository_inputs",
    "validate_parser_run_request",
    "validate_parser_run_result",
    "validate_parser_validation_issue",
    "validate_parser_validation_issue_collection",
)
